// This file was procedurally generated by Weaver. Any modifications will be overwritten.
// This file was generated using Weaver Lite. You can purchase Weaver Pro via the Welcome Panel in the Weaver Window.

#pragma warning disable // All.

namespace Weaver
{
    /// <summary>This class was procedurally generated by Weaver.</summary>
    public static class Animations
    {
        #region Hash Constants

        /// <summary>Area_FadeOut</summary>
        public const int Area_FadeOut = 2085803280;

        /// <summary>Area_Hide</summary>
        public const int Area_Hide = 1142933929;

        /// <summary>Area_Show</summary>
        public const int Area_Show = -762782845;

        /// <summary>attacking</summary>
        public const int attacking = 60754182;

        /// <summary>Aura_Idle</summary>
        public const int Aura_Idle = -1809965874;

        /// <summary>Aura_Play</summary>
        public const int Aura_Play = 380860257;

        /// <summary>bgMoves</summary>
        public const int bgMoves = -697799301;

        /// <summary>Bush_Destroy</summary>
        public const int Bush_Destroy = 1889570149;

        /// <summary>Bush_Idle</summary>
        public const int Bush_Idle = 753629815;

        /// <summary>damage</summary>
        public const int damage = 298341484;

        /// <summary>dash</summary>
        public const int dash = -1687233280;

        /// <summary>Dash</summary>
        public const int Dash = 995914302;

        /// <summary>dead</summary>
        public const int dead = -316323548;

        /// <summary>Dir_x</summary>
        public const int Dir_x = 435664310;

        /// <summary>Dir_y</summary>
        public const int Dir_y = 1861256480;

        /// <summary>E</summary>
        public const int E = -726377838;

        /// <summary>Enemy_Damage</summary>
        public const int Enemy_Damage = -1972244118;

        /// <summary>Enemy_Idle</summary>
        public const int Enemy_Idle = -1225868166;

        /// <summary>Enemy_Walk</summary>
        public const int Enemy_Walk = -413437126;

        /// <summary>FontBlinking</summary>
        public const int FontBlinking = -1474800037;

        /// <summary>Ghost Fade Out</summary>
        public const int GhostFadeOut = 1060776208;

        /// <summary>GhostEffect</summary>
        public const int GhostEffect = -269950883;

        /// <summary>Idle</summary>
        public const int Idle = 2081823275;

        /// <summary>littleChest_idle</summary>
        public const int littleChest_idle = -1007882085;

        /// <summary>littleChest_open</summary>
        public const int littleChest_open = -1145518550;

        /// <summary>littleChest_Open_Idle</summary>
        public const int littleChest_Open_Idle = -1209420233;

        /// <summary>loading</summary>
        public const int loading = 1465923764;

        /// <summary>Moving</summary>
        public const int Moving = 949806512;

        /// <summary>movX</summary>
        public const int movX = -1219069079;

        /// <summary>movY</summary>
        public const int movY = -1068413953;

        /// <summary>Planta_Destroy</summary>
        public const int Planta_Destroy = -980714160;

        /// <summary>Planta_Idle</summary>
        public const int Planta_Idle = 1778719410;

        /// <summary>Player_Attack</summary>
        public const int Player_Attack = 1813181734;

        /// <summary>Player_Damage</summary>
        public const int Player_Damage = 974818417;

        /// <summary>Player_Idle</summary>
        public const int Player_Idle = 1485882831;

        /// <summary>Player_Slash</summary>
        public const int Player_Slash = 1632421963;

        /// <summary>Player_Walk</summary>
        public const int Player_Walk = 153422479;

        /// <summary>receive item</summary>
        public const int receiveitem = 1505267080;

        /// <summary>Receive_Item</summary>
        public const int Receive_Item = -1707504048;

        /// <summary>splash-anim</summary>
        public const int splashanim = 444712288;

        /// <summary>Walk</summary>
        public const int Walk = 765711723;

        /// <summary>walking</summary>
        public const int walking = -1472183017;

        /// <summary>Walking</summary>
        public const int Walking = 1744665739;

        /// <summary>Get the name of the specified 'state' using HashToString.</summary>
        public static string GetName(this UnityEngine.AnimatorStateInfo state) => HashToString(state.shortNameHash);

        /// <summary>Get the state or parameter name associated with the specified 'hash' value.</summary>
        public static string HashToString(int hash)
        {
            switch (hash)
            {
                case Area_Show: return "Area_Show";
                case Area_Hide: return "Area_Hide";
                case Area_FadeOut: return "Area_FadeOut";
                case Aura_Idle: return "Aura_Idle";
                case Aura_Play: return "Aura_Play";
                case Bush_Idle: return "Bush_Idle";
                case Bush_Destroy: return "Bush_Destroy";
                case Enemy_Idle: return "Enemy_Idle";
                case Enemy_Walk: return "Enemy_Walk";
                case Enemy_Damage: return "Enemy_Damage";
                case movX: return "movX";
                case movY: return "movY";
                case walking: return "walking";
                case damage: return "damage";
                case GhostFadeOut: return "Ghost Fade Out";
                case E: return "E";
                case littleChest_idle: return "littleChest_idle";
                case littleChest_open: return "littleChest_open";
                case littleChest_Open_Idle: return "littleChest_Open_Idle";
                case Planta_Idle: return "Planta_Idle";
                case Planta_Destroy: return "Planta_Destroy";
                case Player_Idle: return "Player_Idle";
                case Player_Walk: return "Player_Walk";
                case Player_Attack: return "Player_Attack";
                case Player_Slash: return "Player_Slash";
                case Dash: return "Dash";
                case Player_Damage: return "Player_Damage";
                case Receive_Item: return "Receive_Item";
                case Walking: return "Walking";
                case attacking: return "attacking";
                case loading: return "loading";
                case dash: return "dash";
                case dead: return "dead";
                case receiveitem: return "receive item";
                case GhostEffect: return "GhostEffect";
                case FontBlinking: return "FontBlinking";
                case Idle: return "Idle";
                case Walk: return "Walk";
                case Moving: return "Moving";
                case Dir_x: return "Dir_x";
                case Dir_y: return "Dir_y";
                case splashanim: return "splash-anim";
                case bgMoves: return "bgMoves";
                default: return null;
            }
        }

        #endregion
    }
}
